# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=4)),
                ('stop_id', models.IntegerField(verbose_name='Stop ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'inbound'), ('OUTBOUND', 'outbound')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TickerStation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name="Location (store's name, etc)")),
                ('address', models.CharField(max_length=100, verbose_name='Address for Location')),
                ('contact_notes', models.TextField(verbose_name='Contact details (phone, email, etc) of Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
