# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstation',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 21, 13, 2, 262207)),
            preserve_default=False,
        ),
    ]
