# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerstation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickerstation',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address for Location'),
        ),
        migrations.AlterField(
            model_name='tickerstation',
            name='contact_notes',
            field=models.TextField(blank=True, verbose_name='Contact details (phone, email, etc) of Location'),
        ),
        migrations.AlterField(
            model_name='tickerstation',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
