# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_prediction_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=8),
        ),
    ]
